# Coolify Deployment Configuration for ChimeraBot
# This file provides optimized settings for Coolify deployment

version: "3.8"

services:
  chimerabot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chimerabot
    restart: unless-stopped
    environment:
      # Trading Mode - Set these in Coolify Secrets
      - ENABLE_REAL_TRADING=${ENABLE_REAL_TRADING:-false}
      - BINANCE_TESTNET=${BINANCE_TESTNET:-true}
      
      # Clean Start (optional)
      - FORCE_CLEAN_START=${FORCE_CLEAN_START:-false}
      
      # Binance API (Required - Set as Secrets in Coolify)
      - BINANCE_API_KEY=${BINANCE_API_KEY}
      - BINANCE_SECRET_KEY=${BINANCE_SECRET_KEY}
      
      # Telegram (Required - Set as Secrets in Coolify)
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      
      # AI System (Optional)
      - AI_ENABLED=${AI_ENABLED:-true}
      - AI_PRIMARY_PROVIDER=${AI_PRIMARY_PROVIDER:-deepseek}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY:-}
      - GROQ_API_KEY=${GROQ_API_KEY:-}
      - GEMINI_API_KEY=${GEMINI_API_KEY:-}
      
      # Reddit (Optional)
      - REDDIT_CLIENT_ID=${REDDIT_CLIENT_ID:-}
      - REDDIT_CLIENT_SECRET=${REDDIT_CLIENT_SECRET:-}
      - REDDIT_USER_AGENT=${REDDIT_USER_AGENT:-ChimeraBot/1.0}
      
      # Database (default: SQLite)
      - DATABASE_URL=${DATABASE_URL:-sqlite:///data/chimerabot.db}
      
      # Scanning Configuration
      - MAX_COINS_TO_SCAN=${MAX_COINS_TO_SCAN:-600}
      - SCAN_INTERVAL_SECONDS=${SCAN_INTERVAL_SECONDS:-300}
      
      # Logging
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - LOG_FILE=${LOG_FILE:-logs/chimerabot.log}
      
      # Trading Parameters
      - BTC_CORRELATION_THRESHOLD=${BTC_CORRELATION_THRESHOLD:-0.7}
      - NOTIFY_ON_NO_SIGNAL=${NOTIFY_ON_NO_SIGNAL:-true}
      
      # Advanced Settings
      - TRADE_MANAGER_SLEEP_SECONDS=${TRADE_MANAGER_SLEEP_SECONDS:-10}
      - MAX_RETRIES=${MAX_RETRIES:-3}
      - RETRY_DELAY_SECONDS=${RETRY_DELAY_SECONDS:-5}
    
    volumes:
      # Persist data and logs - Coolify will handle volume mounts
      - chimerabot_data:/app/data
      - chimerabot_logs:/app/logs
    
    # Resource limits for optimal performance
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'
    
    # Health check
    healthcheck:
      test: ["CMD-SHELL", "python -c 'import sys; sys.path.append(\"/app\"); print(\"Health check OK\")'"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  chimerabot_data:
    driver: local
  chimerabot_logs:
    driver: local
